FROM pytorch/pytorch:2.0.1-cuda11.7-cudnn8-devel

RUN apt-get update && \
    apt-get install -y vim  && \
    pip install jupyterlab  && \
    pip install torchvision && \
    pip install torchtext   && \
    pip install lightning   && \
    apt-get install -y git  && \
    git config --global user.name  "Yixiang Gao" && \
    git config --global user.email "yg5d6@umsystem.edu"